# kubernetes/deployment-template.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: email-alert-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: email-alert
  template:
    metadata:
      labels:
        app: email-alert
    spec:
      containers:
      - name: app
        image: us-central1-docker.pkg.dev/ai-learning-495017/ai-sre-repo/email-alert-app:latest
        ports:
        - containerPort: 8000
---
apiVersion: v1
kind: Service
metadata:
  name: email-alert-service
spec:
  type: LoadBalancer
  selector:
    app: email-alert
  ports:
    - port: 80
      targetPort: 8000
