# .github/workflows/cd-gcp.yml
name: CD - GCP

on:
  workflow_dispatch:
  push:
    branches:
      - 'release/gcp'

env:
  PROJECT_ID: ai-learning-495017
  PROJECT_NUMBER: '663314858590'
  REGION: us-central1
  REPOSITORY: ai-sre-repo
  IMAGE_NAME: email-alert-app

jobs:
  deploy-to-gcp:
    name: Deploy to GCP
    runs-on: ubuntu-latest
    permissions:
      contents: 'read'
      id-token: 'write' # Required for OIDC

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Authenticate to GCP via OIDC
        id: 'auth'
        uses: 'google-github-actions/auth@v2'
        with:
          workload_identity_provider: 'projects/${{ env.PROJECT_NUMBER }}/locations/global/workloadIdentityPools/github-pool/providers/github-provider'
          service_account: 'github-actions-deployer@${{ env.PROJECT_ID }}.iam.gserviceaccount.com'

      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v2

      - name: Configure Docker for GAR
        run: |
          gcloud auth configure-docker ${{ env.REGION }}-docker.pkg.dev --quiet

      - name: Build and Push Docker Image
        run: |
          IMAGE_TAG=${{ env.REGION }}-docker.pkg.dev/${{ env.PROJECT_ID }}/${{ env.REPOSITORY }}/${{ env.IMAGE_NAME }}:${{ github.sha }}
          docker build -t $IMAGE_TAG .
          docker push $IMAGE_TAG

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Terraform Apply
        id: apply
        working-directory: ./infra/environments/gcpprod
        run: |
          terraform init
          terraform apply -auto-approve -var="project_id=${{ env.PROJECT_ID }}" -var="region=${{ env.REGION }}"

      - name: Deploy to GKE
        run: |
          gcloud container clusters get-credentials ai-sre-cluster --region ${{ env.REGION }}
          IMAGE_TAG=${{ env.REGION }}-docker.pkg.dev/${{ env.PROJECT_ID }}/${{ env.REPOSITORY }}/${{ env.IMAGE_NAME }}:${{ github.sha }}
          sed -e "s|DOCKER_IMAGE_PLACEHOLDER|$IMAGE_TAG|g" kubernetes/deployment-template.yaml | kubectl apply -f -
